
window.__LANG__ = {
  en: {
    nav_home: "Home",
    nav_policies: "Shop Policies",
    nav_custom: "Custom Orders",
    nav_about: "About",
    nav_contact: "Contact",
    tagline: "feito for mano",
    hero_copy: "Handmade ceramics made with love — no two pieces are the same.<br><em>No piece is the same — feito a mano, feito for YOU!</em>",
    cta_custom: "Request a Custom",
    cta_policies: "Shop Policies",
    featured: "Featured Pieces",
    filter_all: "All",
    filter_mugs: "Mugs",
    filter_bowls: "Bowls",
    filter_trays: "Trays",
    filter_vases: "Vases",
    badge_new: "NEW",
    badge_sold: "SOLD OUT",
    restock: "Restock: add date",
    buy_etsy: "Buy on Etsy",
    view: "View",
    gallery_hint: "Swap photos in <code>assets/img/</code> and set your Etsy links on each “Buy on Etsy” button.",
    nl_label: "Join our newsletter for drops & markets:",
    nl_btn: "Subscribe",
    policies_title: "Shop Policies",
    pol_proc: "Processing & Turnaround Time",
    pol_proc_1: "Ready‑to‑ship items: ship within 3–5 business days.",
    pol_proc_2: "Custom orders: estimated 2–4 weeks depending on complexity (timeline provided).",
    pol_proc_3: "We’ll message you if there are any delays.",
    pol_ship: "Shipping Policies",
    pol_ship_1: "Careful packaging: bubble wrap, eco‑friendly paper, sturdy boxes.",
    pol_ship_2: "Carriers: USPS Priority (UPS for larger orders). Tracking provided.",
    pol_ship_3: "Carrier delays are outside our control; we’ll help with claims if needed.",
    pol_custom: "Custom Orders",
    pol_custom_1: "Full payment up front for custom listings.",
    pol_custom_2: "Progress photos on request.",
    pol_custom_3: "No major changes after work begins (small tweaks may be possible).",
    pol_custom_4: "No returns or refunds on custom items.",
    pol_returns: "Returns & Exchanges",
    pol_returns_1: "Because each piece is handmade and fragile, returns and exchanges aren’t accepted.",
    pol_returns_2: "If something arrives damaged, contact us within 48 hours with photos and keep the packaging. We’ll replace when possible or refund.",
    pol_cancel: "Cancellations",
    pol_cancel_1: "Cancellations accepted within 24 hours of purchase.",
    pol_cancel_2: "After 24 hours—or once a custom starts—cancellations aren’t guaranteed.",
    pol_care: "Care Instructions",
    pol_care_1: "Hand‑wash recommended.",
    pol_care_2: "Microwave use not recommended unless otherwise stated.",
    pol_care_3: "Handle with love.",
    pol_comm: "Communication",
    pol_comm_1: "We reply within 1–2 business days.",
    pol_comm_2: "You’ll be notified if any major changes affect your order.",
    custom_title: "Custom Orders",
    custom_intro: "Have a vision? Tell us about your dream piece—colors, size, and any reference photos.",
    label_name: "Full Name",
    label_email: "Email",
    label_type: "Piece Type",
    label_colors: "Colors / Glaze Ideas",
    label_notes: "Notes",
    request_quote: "Request Quote",
    about_title: "About",
    about_copy: "<strong>Feito a Mano</strong> means “made by hand.” We add a playful twist—<em>feito for mano</em>—because we craft for friends. Our priority is function: strong, smoothed shapes built to last, finished with warm, retro character.",
    contact_title: "Contact",
    contact_copy: "Questions about an order, wholesale, or a custom idea? Send a note and we’ll get back within one business day.",
    label_message: "Message",
    send: "Send"
  },
  pt: {
    nav_home: "Início",
    nav_policies: "Políticas da Loja",
    nav_custom: "Encomendas",
    nav_about: "Sobre",
    nav_contact: "Contato",
    tagline: "feito para mano",
    hero_copy: "Cerâmicas feitas com amor — nenhuma peça é igual à outra.<br><em>Feito à mão, feito para você!</em>",
    cta_custom: "Pedir Encomenda",
    cta_policies: "Políticas da Loja",
    featured: "Peças em Destaque",
    filter_all: "Tudo",
    filter_mugs: "Canecas",
    filter_bowls: "Tigelas",
    filter_trays: "Bandejas",
    filter_vases: "Vasos",
    badge_new: "NOVO",
    badge_sold: "ESGOTADO",
    restock: "Reestoque: adicionar data",
    buy_etsy: "Comprar no Etsy",
    view: "Ver",
    gallery_hint: "Troque as fotos em <code>assets/img/</code> e adicione seus links do Etsy em cada botão.",
    nl_label: "Assine para novidades e feiras:",
    nl_btn: "Assinar",
    policies_title: "Políticas da Loja",
    pol_proc: "Processamento e Prazo",
    pol_proc_1: "Prontos para envio: 3–5 dias úteis.",
    pol_proc_2: "Encomendas: 2–4 semanas, conforme a complexidade (enviamos o cronograma).",
    pol_proc_3: "Avisaremos sobre qualquer atraso.",
    pol_ship: "Envio",
    pol_ship_1: "Embalagem cuidadosa: plástico bolha, papel ecológico e caixas resistentes.",
    pol_ship_2: "Transportadoras: USPS Priority (UPS para pedidos grandes). Enviamos rastreio.",
    pol_ship_3: "Atrasos do transportador fogem do nosso controle; ajudamos com reclamações.",
    pol_custom: "Encomendas",
    pol_custom_1: "Pagamento integral antecipado.",
    pol_custom_2: "Fotos do progresso sob demanda.",
    pol_custom_3: "Sem mudanças grandes após o início (ajustes pequenos podem ser possíveis).",
    pol_custom_4: "Sem devoluções para peças sob encomenda.",
    pol_returns: "Trocas e Devoluções",
    pol_returns_1: "Por serem artesanais e frágeis, não aceitamos trocas ou devoluções.",
    pol_returns_2: "Se chegar danificado, avise em até 48h com fotos e guarde a embalagem. Trocamos quando possível; se não, reembolsamos.",
    pol_cancel: "Cancelamentos",
    pol_cancel_1: "Cancelamentos em até 24 horas após a compra.",
    pol_cancel_2: "Depois disso — ou após o início da peça — não garantimos.",
    pol_care: "Cuidados",
    pol_care_1: "Lavar à mão recomendado.",
    pol_care_2: "Micro-ondas não recomendado, salvo indicação.",
    pol_care_3: "Manuseie com carinho.",
    pol_comm: "Comunicação",
    pol_comm_1: "Respondemos em 1–2 dias úteis.",
    pol_comm_2: "Avisaremos sobre qualquer mudança importante.",
    custom_title: "Encomendas",
    custom_intro: "Conte sua ideia — cores, tamanho e referências.",
    label_name: "Nome Completo",
    label_email: "E-mail",
    label_type: "Tipo de Peça",
    label_colors: "Cores / Esmaltes",
    label_notes: "Observações",
    request_quote: "Solicitar Orçamento",
    about_title: "Sobre",
    about_copy: "<strong>Feito a Mano</strong> significa “feito à mão”. Com um toque brincalhão — <em>feito for mano</em> — criamos para amigos. A prioridade é a função: formas firmes e suaves, feitas para durar, com um clima retrô acolhedor.",
    contact_title: "Contato",
    contact_copy: "Dúvidas sobre pedidos, atacado ou encomendas? Envie uma mensagem — respondemos em até um dia útil.",
    label_message: "Mensagem",
    send: "Enviar"
  }
};
